version: "3.7"

services:
  application:
    container_name: backmonstrao
    image: backmonstrao
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080